### Application Configuration ###
spring.application.name=easybank-api

### Database Configuration ###
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/easybankapidb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

### Security Configuration ###
server.port=443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=easybankcert
server.servlet.session.cookie.max-age=20m