spring.application.name=social-login

### Security Configuration ###
server.port=443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=easybankcert
server.servlet.session.cookie.max-age=20m